# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   schedule:
    - cron: 0 6 * * 1,2,3,4,5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:        
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: --reference-doc templates/reference.docx --output=output/document.docx src/sample_doc.md
      - uses: docker://pandoc/core:2.9
        with:
          args: --reference-doc templates/reference.potx --output=output/presentation.pptx src/sample_ppt.md
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output

